[package]
name = "dataspace"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
iced = {version="0.13.1", features = ["debug", "highlighter", "tokio", "lazy", "canvas"]}
lazy_static = "1.5.0"
rand = "0.8.5"
tracing-subscriber = "0.3.18"

[build-dependencies]
cc="*"

[[bin]]
name = "neutrino"
path = "src/main.rs"
#crate-type = ["cdylib"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"

[profile.wasm-release]
inherits = "release"
opt-level = "s"
strip = "debuginfo"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]
